[package]
name = "sfc"
version = "0.1.0"
authors = ["SplittyDev <splittydev@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"